platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: 'v16.1.0'

inputs:
  - name: bosh-package-cf-cli-release
  - name: bosh-package-golang-release
  - name: cf-performance-tests-release
  - name: cf-performance-tests-release-version
  - name: cf-performance-tests-pipeline

outputs:
  - name: cf-performance-tests-release-output

run:
  path: cf-performance-tests-pipeline/ci/tasks/create-final-bosh-release/task.sh

params:
  GIT_COMMIT_EMAIL:
  GIT_COMMIT_USERNAME:
